### ISSUE TITLE
Training log

### ISSUE THREAD

**Issue by rumusan** [soo89/ISD-SSD#1]
Thanks for the great work! However, I encountered some difficulties during reproducing this paper based on other codebase, like mmdetection. Could you share the training log? So that I can check the problem. Many thanks.

**Comment by soo89** [comment]
Thanks for your interest.

[loss_text.txt](https://github.com/soo89/ISD-SSD/files/5019611/loss_text.txt)

**Comment by rumusan** [comment]
Thanks for your help.
