### ISSUE TITLE
Isn't loc_shuffle going to be the same as loc_flip ?

### ISSUE THREAD

**Issue by DereureErwan** [soo89/ISD-SSD#2]
Hi, thanks a lot for the great work!

I was digging in the code and I noticed this line:
` loc_shuffle = loc_flip.view(loc_shuffle.size(0), -1, 4)` (in isd.py line 182).

Isn't it going to force the fixmatch loss to be 0?

Thank you again very much!

**Comment by soo89** [comment]
thanks for your interest.

I am sorry for making you confused.

We compute CSD loss with (loc, loc_flip/ conf, conf_flip).

For flip computation, we compute the horizontal flip for loc_flip and conf_flip (L170-175).

For ISD loss, however, we should have unflipped results (loc_shuffle, conf_shuffle/L168-169) for the flipped images.

And, we compute ISD loss with (loc, loc_shuffle, loc_interpolation / conf/ conf_shuffle, conf_interpolation).
